FROM python:3.10

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN python -m spacy download es_core_news_sm && \
    python -m spacy download en_core_web_sm && \
    python -m spacy download fr_core_news_sm && \
    python -m spacy download it_core_news_sm

RUN python -m nltk.downloader -d /usr/local/share/nltk_data stopwords

ENV NLTK_DATA=/usr/local/share/nltk_data

COPY ./server ./server

CMD ["uvicorn", "server.main:app", "--host", "0.0.0.0", "--port", "8000"]
