FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Descargar modelo de SpaCy
RUN python -m spacy download en_core_web_sm

# Descargar corpus de NLTK necesario
RUN python -m nltk.downloader stopwords

COPY . .

EXPOSE 8000

CMD ["uvicorn", "server.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]